server:
  port: 8082
spring:
  application:
    name: comment-service
  # mvc:
  #   cors:
  #     mappings:
  #       "/**":
  #         allowedOrigins: "*"
  #         allowedMethods: "*"
  #         allowedHeaders: "*"
  #         allowCredentials: true