server:
  port: 8082
spring:
  application:
    name: comment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/comment_db
  mvc:
    cors:
      mappings:
        "/**":
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"
          allowCredentials: true